CREATE TABLE ITEM
(
    ID                NUMBER PRIMARY KEY,
    NAME              NVARCHAR2(50)             NOT NULL,
    DATE_CREATED      DATE DEFAULT CURRENT_DATE NOT NULL,
    LAST_UPDATED_DATE DATE DEFAULT CURRENT_DATE NOT NULL,
    DESCRIPTION       NVARCHAR2(300)            NOT NULL
);
